feat!: Allow enforcing non-empty array parameters in config
When using array parameters (including array spread and pick), providing
an empty array to a parameter will usually cause a crash at runtime due
to a syntax error.

For the following query, if an empty array is provided for userIds:

```
/*
  @name GetNotifications
  @param userIds -> (...)
*/
SELECT * FROM notifications WHERE id in :userIds!
```

As the query at runtime becomes:

```
SELECT * FROM notifications WHERE id in ()
```

Which results in:

```
ERROR:  syntax error at or near ")"
```

Therefore, this config forces the generated parameter type to only allow
non-empty arrays, i.e. the type `[T, ...T[]]` rather than `T[]`.